# Generated by Django 2.0.13 on 2019-07-11 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('for_floor', models.IntegerField()),
                ('for_room', models.IntegerField()),
                ('body', models.TextField()),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raised_by', models.CharField(max_length=30)),
                ('body', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('RESOLVED', 'RESOLVED')], default='PENDING', max_length=1)),
                ('date_of_raising', models.DateTimeField(auto_now=True)),
                ('date_of_resolving', models.DateTimeField(null=True)),
            ],
        ),
    ]
