# Generated by Django 2.0.13 on 2019-07-11 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supervisor_portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='for_room',
            field=models.CharField(max_length=10),
        ),
    ]
