# Generated by Django 2.0.13 on 2019-07-14 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supervisor_portal', '0002_auto_20190711_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
